---
title: "Integrated SDM"
author: "Mari Roberts and Jessica Spencer"
date: "1/8/2019"
output: pdf_document
---

```{r}
########################################
# Load packages or install packages if they don't exist
########################################

requiredPackages = c('raster',
                     'fields',
                     'mvtnorm',
                     'matrixStats', # matrix functions
                     'readr', # read files
                     'rgdal', 
                     'ggplot2', # visualization
                     'dplyr', # data manipularion
                     'tidyverse',
                     'rgbif', # import ad hoc data from GBIF
                     'tidyr' # data tidying
                     ) 
for(p in requiredPackages){
  if(!require(p,character.only = TRUE)) install.packages(p)
  library(p,character.only = TRUE)
}

# source("tiger/analysis-r/functions_modified.R") # read functions

########################################
# Import data
########################################

###
# 1 Site Occupancy
###

# 394 unique grid cells
s.o.original = read.csv("tiger/data/Tiger_observation_entry_9_SS_Observations_SUMATRA.csv")

###
# 2 Camera Trap
###

# BBSNP2015 CT data
# 8 unique grid cells
tiger.CT.observations <- read.csv("tiger/data/Tiger_observation_entry_9_CT_observations_BBSNP_V2.csv")
tiger.CT.entry <- read.csv("tiger/data/Tiger_observation_entry_9_CT_deployments_latlon_BBSNP.csv")

# Leuser data doesn't have observation date
tiger.CT.observations2 <- read.csv("tiger/data/Tiger_observation_entry_9_CT_deployments_latlon_Leuser_V2.csv")
# tiger.CT.entry2 <- read.csv("tiger/data/Tiger_observation_entry_9_CT_deployments_observations_Leuser_V2.csv")

###
# 3 Ad Hoc
###

# 29 unique grid cells
pb.original <- read.csv("tiger/data/Ad Hoc v9 Sumatra 25NOV2019_V2.csv", skip = 1)

########################################
# Sumatran Grid Cells
########################################

# import Sumatra shapefile of gridcells 
unzip("tiger/data/sumatragridmrgd.zip")
sumatra.map <- readOGR(dsn = ".", layer = "sumatragridmrgd")

# import shapefile of camera lat long and corresponding grid cells
# only includes grid cells for Puspurini data, not Leuser - 8 unique grid cells
unzip("tiger/data/camera_latlon_gridcode.zip")
camera.gridcode <- readOGR(dsn = ".", layer = "camera_latlon_gridcode")
camera.gridcode <- as.data.frame(camera.gridcode)

########################################
# Shapefiles of Covariates
########################################

# prob.zip provided by Kim Fischer

# # create list of all .shp files in folder (case of "shp" matters)
filenames <- list.files(path="tiger/data/prob", pattern=".*shp")

# read in each shp file
for (i in 1:length(filenames)){
  assign(filenames[i], rgdal::readOGR(paste("tiger/data/prob/", filenames[i], sep=''))
  # figure out how to raster in this loop?
  )}

# convert to raster layer
ct.hii <- raster(Tiger_observation_entry_9_CT_deployments_latlon_BBSNP_hii.shp)
ct.srtm<-raster(Tiger_observation_entry_9_CT_deployments_latlon_BBSNP_srtm.shp)
ct.hii.Leuser<-raster(Tiger_observation_entry_9_CT_deployments_latlon_Leuser_V2_hii.shp)
ct.srtm.Leuser<-raster(Tiger_observation_entry_9_CT_deployments_latlon_Leuser_V2_srtm.shp)

# we need one covariate value per grid point? 
WibiPuspa_1000pts_hii.shp<-raster(WibiPuspa_1000pts_hii.shp)
WibiPuspa_1000pts_srtm.shp<-raster(WibiPuspa_1000pts_srtm.shp)

proj4string(sumatra.map) <- CRS('+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0')
### cut Bioclim
hii_crop <- crop(ct.hii, sumatra.map) #crop
# extent(hii_crop) <- alignExtent(hii_crop, Prec) # Aligne extent
hii_cut <- mask(hii_crop, sumatra.map)# mask

########################################
# s.occupancy
# s.detection
########################################

# standarize using scale?
s.occupancy <- stack(scale(hii_crop, center=TRUE, scale=TRUE))
s.detection <- stack(scale(hii_crop, center=TRUE, scale=TRUE))

########################################
# so.occupancy
# so.detection
########################################

so.occupancy <- read.csv("tiger/data/prob/Tiger_observation_entry_9_SS_Observations_SUMATRA_srtm_hii.csv")

so.occupancy <- so.occupancy %>% select(grid.cell.label, 
                                        elevation = sumatragridmrgd2_centroids_srtm_srtm_1,
                                        hii = sumatragridmrgd2_centroids_hii_hii_1) %>% 
                distinct(grid.cell.label, .keep_all = TRUE) %>% select(-grid.cell.label)

# so.detection <- so.occupancy %>% select(elevation,
#                                        hii)

# plot to check ???
# plot(s.occupancy) 

########################################
# Site occupancy data
########################################

# rename variables
s.o.original = rename(s.o.original, 
                      num.surveys = X..replicates.surveyed,
                      grid = grid.cell.label, 
                      replicate = replicate..)

s.o.original = s.o.original %>% select(-survey.id) #same on every column

#unique id on grid cel & replicate number
s.o.original$id.survey = cumsum(!duplicated(s.o.original[2:4])) 

max(s.o.original$num.surveys) #98

# Take all the surveys with NO signs
# create new row for each survey that took 
a = s.o.original %>% 
  filter(observation == 0) %>% 
  crossing(survey =(1:98)) %>% #max number of surveys done
  mutate(good.survey = ifelse(survey>num.surveys, NA, 1)) %>% 
  na.omit()
a = dplyr::select(a,-c(good.survey))

# expand the 1's
b = s.o.original %>% 
  filter(observation == 1) %>% 
  select(-observation) %>% 
  crossing(survey =(1:98)) %>% 
  mutate(good.survey = ifelse(survey>num.surveys, NA, 1)) %>%
  na.omit() %>%
  mutate(observation = ifelse(survey!=replicate, 0, 1))

b = dplyr::select(b,-c(good.survey)) 
#View(s.o.original)

# combine the two
so.filled =rbind(a,b)
so.filled_a = 
  dplyr::select(so.filled,-c(replicate)) %>%    
  distinct(survey,
           observation,
           id.survey,
           .keep_all = T)

#find the overlapping observations
onlyOnes = filter(so.filled_a, observation ==1)
onlyZs = filter(so.filled_a, observation == 0)

reps = plyr::match_df( 
  onlyZs,onlyOnes,
  on = c("id.survey","survey"))
# subtract overlapping observations from the expanded set
final.filled = setdiff(so.filled_a,reps)

strip.so = dplyr::select(final.filled,observation,survey,grid, id.survey)

y.so = spread(strip.so, survey, observation)

# remove variables grid and id.survey
y.so <- y.so %>% select(-grid, -id.survey)

test = matrix(0,ncol = 2, nrow = dim(y.so)[1])
test[,1] = rowSums(ifelse(is.na(y.so)==FALSE,1,0)) # number of times zero or one
test[,2] = rowSums(ifelse(is.na(y.so)==FALSE & y.so == 1,1,0)) # number of times tiger was seen 

# is.complete=complete.cases(so.occupancy)&complete.cases(test)

is.complete = which(so.occupancy$hii != "NaN")

so.occupancy = so.occupancy[is.complete,]# only use complete cases

so.occupancy$elevation <- tr(so.occupancy$elevation)
so.occupancy$hii <- tr(so.occupancy$hii)

test=test[is.complete,]# only use complete cases
# so.detection=so.detection[is.complete,]# only use complete cases
# y.so=y.so[is.complete,]# only use complete cases
area.so =pi*0.04

y.so <- test

X.so=cbind(rep(1, nrow(as.matrix(so.occupancy))), so.occupancy) # 3 columns and 381 rows (2 columns are covariates)

so.fit=so.model(X.so,y.so)

printList(so.fit)
```

  Parameter name       Value Standard error
1          beta0 -0.06895547     0.07899580
2      elevation -0.04392090     0.08024163
3            hii -0.12030062     0.08313676
4 alphaintercept -2.49739676     0.04578337

[1] 0
[1] 2381.814

# Presence Only Model

```{r}

pb <- pb.original %>% select(grid = cell.label, 
                    observation.date,
                    observation = Report)

# turn pb into raster? in the Koshkina paper, we have coordinates
# pb.loc = 

pb.occupancy=extract(s.occupancy,pb.loc)
pb.detection=extract(s.detection,pb.loc)

is.complete.pb=complete.cases(pb.detection)&complete.cases(pb.occupancy)
pb.detection=pb.detection[is.complete.pb,]
pb.occupancy=pb.occupancy[is.complete.pb,]

#Analyzing Presence-Only data
# pb.fit=pb.ipp(X.po, W.po,X.back, W.back)
# pb.fit
```

# Integrated Model

```{r}
# Analyzing presence-only data AND presence-absence data
poANDso.fit=pbso.integrated(X.po, W.po,X.back, W.back,X.so,W.so,y.so)
printList(poANDso.fit)
# Parameter name     Value Standard error
# 1          beta0 103.65297             NA
# 2           alti  45.68099             NA
# 3       bio12_23 -35.95170             NA
# 4        bio1_23  12.70863             NA
# 5         alpha0 -90.97832             NA
# 6           alti -50.84638             NA
# [1] 0
# [1] -7242.244
```
